### ISSUE TITLE
Restoring a Rundown Playlist snapshot breaks rundown order

### ISSUE THREAD

**Issue by ianshade** [nrkno/sofie-core#1034]
`DBRundownPlaylist` has a property called `rundownIdsInOrder`, that references ids of rundowns that belong to the playlist. When restoring a snapshot, ids are replaced with randomly generated values on rundowns, segments, and so on, however it seems that `rundownIdsInOrder` array stays unchanged, and references old rundown ids.

**Comment by Julusian** [comment]
This is fixed in the release50 branch
