### ISSUE TITLE
RFC: Improve GUI Accessibility 

### ISSUE THREAD

**Issue by hummelstrand** [nrkno/sofie-core#1125]
### About me

This RFC is posted by _SuperFly.tv_ on behalf of the _BBC_.

### Use case

Improving the accessibility of the Sofie GUI in order to comply with regulatory requirements. Recommendations for changes  are outlined in the attached report.
[Public Summary of Accessibility Audit report Sofie.pdf](https://github.com/nrkno/sofie-core/files/13953044/Public.Summary.of.Accessibility.Audit.report.Sofie.pdf)

### Proposal

We propose to modify the GUI in order to better cater to accessibility tools. We intend to target _Release 51_.

### Process

The Sofie Team will evaluate this RFC and open up a discussion about it, usually within a week.
- [x] RFC created
- [x] Sofie Team has evaluated the RFC
- [x] A workshop has been planned
- [x] RFC has been discussed in a workshop
- [x] A conclusion has been reached, see comments in thread

**Comment by jstarpl** [comment]
Thank you for submitting this RFC!
(If you haven’t already, please give our [contribution guidelines](https://nrkno.github.io/sofie-core/docs/for-developers/contribution-guidelines/) a read.)

The Sofie NRK Team welcomes this improvement and sees no point in setting up a workshop. We'll keep this RFC open for comments until a PR is opened.

**Comment by hummelstrand** [comment]
### Question to other Sofie users: 
If, as part of the PR, we changed the HTML page title from the currently static "Sofie" to something like "Sofie: Name of Playlist", would that break any existing scripts or logging workflows for any users?

**Comment by hummelstrand** [comment]
PR: https://github.com/nrkno/sofie-core/pull/1138
