### ISSUE TITLE
RFC: Segment budget timing as primary timing in Sofie

### ISSUE THREAD

**Issue by ianshade** [nrkno/sofie-core#1188]
### About me

This RFC is posted on behalf of the BBC.

### Use case

Usage Scenario: As a Director or Presenter I can see a countdown to the end of the Segment alongside the “On Air line” in the Rundown View, in the header-section of the Rundown View, in the Presenter View as well as in the Prompter View.

This mode should be optional and selectable (during ingest, via the blueprints) per Segment, with the default behavior remaining Part-based.

### Proposal

We propose the following changes and addition to Sofie Core:

- `budgetDuration` is moved from Part onto Segment's `segmentTiming`. As far as we know, no use case exists among the users of Sofie where multiple Parts would need to contribute to Segment's budget duration.
- An optional `countdownType` property is added to `segmentTiming`, taking one of the two possible values: `CountdownType.PART_EXPECTED_DURATION` (the default if not specified), `CountdownType.SEGMENT_BUDGET_DURATION`
- During a segment in which `segmentTiming.countdownType === CountdownType.SEGMENT_BUDGET_DURATION` the _Part countdown_ is replaced with _Segment countdown_ in the Rundown View and Presenter View. (Prompter View is TBD as currently it doesn't seem to feature Part countdown)
- Live Status Gateway makes `countdownType` available to its subscribers.

### Process

The Sofie Team will evaluate this RFC and open up a discussion about it, usually within a week.
- [x] RFC created
- [x] Sofie Team has evaluated the RFC
- [ ] A workshop has been planned
- [ ] RFC has been discussed in a workshop
- [ ] A conclusion has been reached, see comments in thread

**Comment by jstarpl** [comment]
Thank you for submitting this RFC!
(If you haven’t already, please give our [contribution guidelines](https://nrkno.github.io/sofie-core/docs/for-developers/contribution-guidelines/) a read.)

We've done a quick huddle in the Sofie Team, and we accept this proposal, without any further discussion. The proposal is backwards-compatible and seems to fit well with the existing architecture.

If anyone else wishes to provide any comments on this RFC or add additional perspectives, please do so in this Issue thread or email me at [jan.starzak@nrk.no](mailto:jan.starzak@nrk.no)

**Comment by jstarpl** [comment]
The contribution PR has been merged, I think we can consider this RFC concluded.
