### ISSUE TITLE
RFC: JSON-schema for AdLib Action editable fields

### ISSUE THREAD

**Issue by thomasslee97** [nrkno/sofie-core#857]
The issue has been opened by SuperFly.tv on behalf of EVS Broadcast Equipment (henceforth EVS).

# Motivation

As part of a project being developed by EVS there is a desire to execute AdLib Actions with data provided by an external system. This requires the external system to understand the parameters of an AdLib Action and to have some way of modifying these parameters.

# Proposal

This comes in two parts: How to expose data, and how to execute an action with some data from an external system.

## Exposing Data

Currently, the `IBlueprintActionManifest` interface has the `userDataManifest` property which contains an `editableFields` property. This looks like exactly the property that an external system should be inspecting to know what can and can't be modified and what constitutes valid data.

However, this currently uses the `ConfigManifestEntry` type, which is an "internal" Sofie type, and would require a 1:1 implementation in an external system. As such, we propose that the `editableFields` property instead use JSON-schema to represent the editable data. This follows nicely from recent work that has [moved device config and mappings](https://github.com/nrkno/sofie-core/pull/837) to use JSON-schema.

This would allow the Live-status Gateway from the [API PR](https://github.com/nrkno/sofie-core/pull/777) to expose this JSON-schema on AdLib Actions, providing external systems with a description of the "arguments" to an AdLib Action in a more widely-understood format than the `ConfigManifestEntry` format that Sofie uses.

## Executing Actions

This work follows naturally from the [Stable API](https://github.com/nrkno/sofie-core/issues/773) discussions and would be a change made after the merging of the [open PR](https://github.com/nrkno/sofie-core/pull/777) (we promise!) to modify the `executeAdLib` method to optionally take a JSON object as an argument. For AdLib Pieces, providing a JSON object would result in the rejection of the request. For AdLib Actions, the object could be validated against the schema and used to extend/override the `userData` property passed to `StudioJobs.ExecuteAction`.

## Scope

As far as we can tell, the `editableFields` property is currently only used within the `ShelfInspector` component, which we believe is deprecated, or in the very least rarely used. We do not fully understand this aspect of Sofie, but if it is still in use then the UI components developed by [#837](https://github.com/nrkno/sofie-core/pull/837) should be sufficient as drop-in replacements for the existing `ConfigManifestEntryComponent` used inside of `ActionItemRenderer.tsx`.

The proposed change to the API would be non-breaking, as it would add an optional property to the body of the request, therefore impact to users of the API would be minimal.

# Request For Comment

- Does anyone currently make use of the inspector?
  - Do they believe that this change would have a negative impact / cause something about their use-case to no longer be possible?
- Does anyone have any objections to this happening "at some point"?
  - Any preference for which release (e.g. "please don't before R51")?
- Is anyone currently investigating any similar problem?
- Thumbs up/down for this idea in general?

**Comment by Julusian** [comment]
> Does anyone currently make use of the inspector?

I am pretty certain that the inspector is not being used by anyone anywhere yet, so I am on board with a breaking change in the `editableFields` property to change its format.

> Does anyone have any objections to this happening "at some point"?

I think this is a good idea, I know that some of the team would like to continue replacing the old `ConfigManifest` system with `JSONSchema`. I think that any release is fine, once #837 is merged.

> Is anyone currently investigating any similar problem?

On the NRK side, I believe a task has not been written for this yet, but I have been meaning to do so at some point.

**Comment by thomasslee97** [comment]
To update on our progress, we have an implementation of this that we are currently testing. We're potentially going to wait for the outcome of https://github.com/nrkno/sofie-core/pull/922 before opening a PR.

**Comment by Julusian** [comment]
@thomasslee97 will they conflict at all? This sounds like a completely different area of the ui to #922 (shelf vs settings)
