### ISSUE TITLE
R50: `winston` types used (but not published) in server-core-integration leads to build-time errors in consuming packages

### ISSUE THREAD

**Issue by alvancamp** [nrkno/sofie-core#925]
It appears that `winston` is now a required type in the `server-core-integration` package as of R50. However, `winston` (or its types) is not published as a `dependency` of `server-core-integration`, so the result is build errors like this:

![image](https://github.com/nrkno/sofie-core/assets/873012/77472712-672b-459a-acd9-a909983da6d8)

**Comment by Julusian** [comment]
I feel like this shouldn't really be a problem in practise as we expect gateways to be using winston, which will result in the types being satisfied once that is installed for the gateways use.

The proper fix here is proabably going to be to do some further refactoring of sever-core-integration to make its usage less repetitive. There was an attempt to move all the winston setup into server-core-integration https://github.com/nrkno/sofie-core/pull/752 which would handle this portion. And in general there is a lot of duplicated code between all the gateways

**Comment by jstarpl** [comment]
I don't think we actually need the `winston.Logger` type. We only use a very small surface of it's API, I've created an internal generic logger interface, which the winston Logger should fulfill, as well, as I expect - many others. Is that an OK solution for everyone?

**Comment by jstarpl** [comment]
We've merged #1025 which I think solves this problem and allows users to use any logging library by using a library with very standard log output methods (even `console` fulfills the interface) or just providing a shim object.
